// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--h6Do_7hFPZrGmT4zlWDN-aNv58ZhYE',
    appId: '1:416849058326:web:14ce1d054ba9e5c797b337',
    messagingSenderId: '416849058326',
    projectId: 'dolooki-fb888',
    authDomain: 'dolooki-fb888.firebaseapp.com',
    storageBucket: 'dolooki-fb888.firebasestorage.app',
    measurementId: 'G-2T109V9H77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgtdiPMHCCCVfzX34ZHLST651iXSS22uY',
    appId: '1:416849058326:android:b7d0259d85cebe0f97b337',
    messagingSenderId: '416849058326',
    projectId: 'dolooki-fb888',
    storageBucket: 'dolooki-fb888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbiG2TwHEdFFRUDZD7goYKt4vhLwIGyU',
    appId: '1:416849058326:ios:3a6ca2991e96864e97b337',
    messagingSenderId: '416849058326',
    projectId: 'dolooki-fb888',
    storageBucket: 'dolooki-fb888.firebasestorage.app',
    iosBundleId: 'com.example.dolooki',
  );

}